---
title: "CV"
author: Rob Jarvis
date: "`r Sys.Date()`"
output: pagedown::html_resume
---


```{r setup, include=FALSE}
# Using the {pagedown} package
# https://pagedown.rbind.io/#resume
# 
# Inspired by Nick Strayer: https://github.com/nstrayer/cv

# Chunk options: https://yihui.org/knitr/options/#chunk-options
knitr::opts_chunk$set(
  echo = FALSE,         # Don't include any R source code in output
  results = "asis"      # R code output written raw into doc, i.e. "as is"
)

library(glue)
library(tidyverse)
```


Aside
=======================================


Contacts
---------------------------------------
- Phone: +61 4xx xxx xxxx
- Email: me@there.com
- LinkedIn: linkedin.com/in/jarvisrob
- GitHub: github.com/jarvisrob
- Twitter: @mrRobJarvis


Skills
---------------------------------------
- Data science
- Consulting
- Machine learning
- Mathematical modelling
- Agile methods
- R, Python and SQL
- Cloud



Something else
---------------------------------------
Maybe can put something else here ...


Main
=======================================


Rob Jarvis {#title}
---------------------------------------
Thirteen years in total building models, applying maths and analysing data to explain, predict and advise how to act. Ten years modelling and researching submarine power systems with Department of Defence. Followed by three years consulting in data science with Telstra Purple and Readify.

Experience in growing teams and growing capabilities.




Conference author and presenter. Author on reports advising federal government and Department of Defence, predominantly on power and energy related aspects of Australia’s future submarine. 

High Distinction average in university studies. Bachelor of Engineering with first class honours in electrical and computer systems engineering. Bachelor of Science in mathematics and physics.





Professional experience
---------------------------------------

### Lead Consultant, Data Science

Telstra Purple (formerly Readify)

N/A

`r lubridate::year(Sys.Date())` - 2018

Consulitng and professional services in data science.

Mainly focused on establishing emerging data practice and business both in data Victoria and nationally.

- Educating the business on data and data science, and the role it plays in our professional services offerings
- Leading teams and being the interface to customers and stakeholders
- Teaching technical and professional skills


• Educating the business on data science and the role it plays in our offerings
• Leading teams and being the interface to our customer
• Teaching technical and professional skills
• Helping career growth, guiding, conducting job retrospectives
• Recruiting new consultants and graduates
• Member of the Victorian leadership group, working on strategy, assisting in operations, being conduit between executives and consultants
• Member of national data leaders' forum
• Pre-sales, meeting customers, writing proposals and tender responses, estimating effort, drafting of statements of work

Highlights:
• Machine learning model of housing prices. Presented to audience at a large customer to explain machine learning and demonstrate our capability. Using Azure Machine Learning tools, Docker, R and Python.

• Data preparation and analysis for a government department. Processing data collected from Telstra antennas, we estimate population locations and movements. Data aggregated to customer's specifications. Using Spark, Hadoop HDFS, Scala, Bash and Power BI.

• Consulting for a manufacturing line. Found data spread across line and business that could be joined to track materials and equipment settings for each run. Proposed building a model from the data, finding the important parameters in determining quality, and recommending ranges for those parameters.

• Tender response for Ambulance Victoria. Designed data architecture in Azure, from ingestion, through data lake and warehouse and into machine learning models. Presented architecture to tender review team.

- Recruitment


### Senior Analyst, Data Science

Readify

N/A

2017

Career change from engineering into data science. First data-specific hire in many years—and the first ever data scientist—in Victoria.

• Modelling of business efficiency for electricity companies. Econometric modelling consistent with how they're evaluated by market regulator. Using R and Shiny.

- Project Batman


### Research Scientist and Engineer

Defence Science and Technology, Department of Defence

N/A

2017 - 2007

Content about the position goes here


Electrical engineering and mathematical analysis forecasting the behaviour of power and energy systems and the consequences for the performance of naval surface ships and submarines.
•	Creation of numerical models, algorithms, and terminology for the simulation of energy flow through a submarine; shared widely within the organisation as the framework for modelling and evaluating submarine performance on metrics such as range and endurance
•	Conference presenter and author of accompanying papers on modelling and simulation topics such as the application of statistical sensitivity analysis, genetic algorithms, multi-objective optimisation techniques, and hardware-in-the-loop simulation
•	Leader of team crafting a state-of-the-art research program into ‘power hardware-in-the-loop systems’, developing methods to integrate real-time simulations of virtual systems with physical items of hardware under test; obtaining and investing over $5 million of funding into equipment, infrastructure, and university collaborations
•	Author on multiple reports advising government, predominantly on aspects of Australia’s future submarine, undertaking numerical modelling for committees that developed the Defence White Papers of 2009 and 2013, and coordinating a technical risk assessment for Federal Cabinet
•	Selection for the internationally-recognised Postgraduate Submarine Design and Acquisition Course at the University College London, including being posted to London for nine weeks
•	Negotiation, establishment, and management of ongoing research partnership with the Queensland University of Technology
•	Deputy laboratory manager charged with workplace health and safety risk assessments, having developed the risk assessment template now recommended for use throughout the division
•	Leader in rewriting organisational policy on electrical safety, negotiating with other committee members, and adapting industry best-practices to meet the unique needs of a research organisation


### University Maths Tutor for Engineering and Science

Monash University

N/A

2006 - 2005

Conducted tutorial classes for students in undergraduate mathematics subjects:
• "Statistics and Integral Transforms for Engineering" (third-year engineering)
• "Multi-variable Calculus" (second-year science)


Education
---------------------------------------

### Bachelor of Engineering (First Class Honours) in Electrical and Computer Systems Engineering

Monash University

Melbourne, Australia

2006 - 2002

Selected achievements and awards:

- High Distinction average
- Studied under a Sir John Monash Scholarship
- Graham Beard Memorial Prize for overall excellence in Electrical and Computer Systems Engineering course, 2006
- RS Components Award for Engineering Excellence for student with highest level of academic excellence, 2006
- Multiple other awards in earlier years of study


### Bachelor of Science in Mathematics and Physics

Monash University

Melbourne, Australia

2006 - 2002

Selected achievements and awards:

- High Distinction in every subject
- Dean’s List Fellowship for Science every year eligible, 2003, 2004, 2005



Certifications
---------------------------------------

### Microsoft Professional Program for Data Science

Microsoft edX

N/A

2019

Content about the cert goes here

### Professional Scrum Master I

Scrum.org

N/A

2018

Content about the cert goes here


